version: '3'
services:
  db:
    image: mysql
    hostname: ${dbdomain}.${host}
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${dbdomain}.${host}
    restart: always
    ports:
      - ${dbport}:${dbport}
    environment:
      MYSQL_ROOT_PASSWORD: ${dbpassword}
      MYSQL_USER: ${dbuser}
      MYSQL_PASSWORD: ${dbpassword}
      MYSQL_DATABASE: ${database}
    tty: true
  sql-service:
    image: ${service}
    hostname: ${domain}.${host}
    container_name: ${domain}.${host}
    ports:
      - ${port}:${port}
    environment:
      - DATABASE=${database} 
      - HOST=${dbdomain}.${host} 
      - PORT=${dbport} 
      - USER=${dbuser}
      - PASSWORD=${dbpassword}
      - SERVICEHOST=${domain}.${host}
      - SERVICEPORT=${port}
    depends_on:
      - db
    tty: true
networks:
  backend:
    driver: bridge